services:
  alertmanager:
    command:
      - --config.file=/config/isc_alertmanager.yml
      - --data.retention=24h
      - --cluster.listen-address=
    depends_on:
      - prometheus
    ports:
      - 9093:9093
    image: prom/alertmanager:v0.20.0
    restart: on-failure
    volumes:
      - ./config/alertmanager:/config
  grafana:
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    image: grafana/grafana:6.7.1
    restart: on-failure
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - ./config/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

  nginx:
    depends_on:
      - prometheus
      - grafana
    image: nginx:1.17.9-alpine
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    hostname: prometheus
    command:
      - --web.enable-lifecycle
      - --config.file=/config/isc_prometheus.yml
      - --storage.tsdb.retention.time=2h
    image: prom/prometheus:v2.17.1
    ports:
      - 9090:9090
    restart: on-failure
    volumes:
      - ./config/prometheus:/config

  node-exporter:
    image: quay.io/prometheus/node-exporter
    hostname: node
    ports:
      - 9100:9100

  iris1:
    image: containers.intersystems.com/intersystems/iris-community:2023.1.1.380.0
    hostname: iris1
    command:
      --check-caps false
    ports:
      - "1972:1972"
      - "52773:52773"
    environment:
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
    volumes:
      - ./iris-target/cpf:/cpf

  iris2:
    image: containers.intersystems.com/intersystems/iris-community:2023.1.1.380.0
    hostname: iris2
    command:
      --check-caps false
    environment:
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
    volumes:
      - ./iris-target/cpf:/cpf

version: '3.7'

