groups:
- name: iris_alerts_rules
  rules:
  - alert: iris_system_alerts
    annotations:
      description: 'iris alerts'
    expr: (idelta(iris_system_alerts_log[5m]) != 0) or (iris_system_alerts_new > 0)
    #expr: (iris_system_alerts_new{cluster="iriscluster"} > 0)
