version: '3.7'

services:
  alertmanager:
    command:
      - --config.file=/config/isc_alertmanager.yml
      - --data.retention=24h
      - --cluster.listen-address=
    depends_on:
      - sam
      - prometheus
    expose:
      - '9093'
    image: prom/alertmanager:v0.20.0
    restart: on-failure
    volumes:
      - ./config/alertmanager:/config
  grafana:
    depends_on:
      - prometheus
    expose:
      - '3000'
    image: grafana/grafana:6.7.1
    restart: on-failure
    volumes:
      - grafdata:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - ./config/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
  sam:
    environment:
      - ISC_DATA_DIRECTORY=/dur/sam
      - ISC_CPF_MERGE_FILE=/config/cpf/merge.cpf
    expose:
      - '51773'
      - '52773'
    hostname: sam
    image: containers.intersystems.com/intersystems/sam:1.0.0.115
    init: true
    restart: on-failure
    volumes:
      - irisdata:/dur
      - ./config:/config

  nginx:
    depends_on:
      - sam
      - prometheus
      - grafana
    image: nginx:1.17.9-alpine
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    command:
      - --web.enable-lifecycle
      - --config.file=/config/isc_prometheus.yml
      - --storage.tsdb.retention.time=2h
    depends_on:
      - sam
    expose:
      - '9090'
    image: prom/prometheus:v2.17.1
    restart: on-failure
    volumes:
      - ./config/prometheus:/config

  iris1:
    image: containers.intersystems.com/intersystems/iris-community:2020.3.0.221.0
    hostname: iris1
    init: true
    ports:
      - "1972:1972"
      - "52773:52773"
    environment:
      - ISC_DATA_DIRECTORY=/dur/iris1
      - ISC_CPF_MERGE_FILE=/config/cpf/merge.cpf
    volumes:
      - irisdata:/dur
      - ./config:/config

volumes:
  grafdata: ~
  irisdata: ~
