global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "./isc_alert_rules.yml"

scrape_configs:
  - job_name: 'iris1'
    metrics_path: /iris1/api/monitor/metrics
    scheme: http
    static_configs:
    - labels:
        cluster: "iriscluster"
      targets:
      - webgateway:80
    relabel_configs:
      - target_label: instance
        replacement: 'iris1'

  - job_name: 'iris2'
    metrics_path: /iris2/api/monitor/metrics
    scheme: http
    static_configs:
    - labels:
        cluster: "iriscluster"
      targets:
      - webgateway:80
    relabel_configs:
      - target_label: instance
        replacement: 'iris2'

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node:9100']