---
services:
  alertmanager:
    command:
      - --config.file=/config/isc_alertmanager.yml
      - --data.retention=24h
      - --cluster.listen-address=
    depends_on:
      - iris
      - prometheus
    expose:
      - '9093'
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    volumes:
      - ./config/alertmanager:/config
  grafana:
    depends_on:
      - prometheus
    expose:
      - '3000'
    image: grafana/grafana:9.1.7
    restart: on-failure
    volumes:
      - grafdata:/var/lib/grafana
      #- ./config/grafana/data:/var/lib/grafana
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - ./config/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
  iris:
    command: '--check-caps false'
    depends_on:
      - iris-init
    environment:
      - ISC_DATA_DIRECTORY=/dur/iconfig
    expose:
      - '1972'
      - '52773'
    ports:
      - "52774:52773"
    hostname: IRIS
    image: containers.intersystems.com/intersystems/sam:2.0.1.181
    init: true
    restart: on-failure
    volumes:
      - irisdata:/dur
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  iris-init:
    command: 'chown -R 51773:51773 /dur && chmod 777 /pro'
    image: busybox
    volumes:
      - irisdata:/dur
      - ./config/prometheus:/pro
  nginx:
    depends_on:
      - iris
      - prometheus
      - grafana
    image: nginx:1.23.1-alpine
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
  prometheus:
    command:
      - --web.enable-lifecycle
      - --config.file=/config/isc_prometheus.yml
      - --storage.tsdb.retention.time=2h
    depends_on:
      - iris
    expose:
      - '9090'
    image: prom/prometheus:v2.39.0
    restart: on-failure
    volumes:
      - ./config/prometheus:/config

  iris1:
    image: containers.intersystems.com/intersystems/iris-community:2023.1.1.380.0
    hostname: iris1
    command:
      --check-caps false
    ports:
      - "1972:1972"
      - "52773:52773"
    environment:
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
    volumes:
      - ./iris-target/cpf:/cpf

  iris2:
    image: containers.intersystems.com/intersystems/iris-community:2023.1.1.380.0
    hostname: iris2
    command:
      --check-caps false
    environment:
      - ISC_CPF_MERGE_FILE=/cpf/merge.cpf
    volumes:
      - ./iris-target/cpf:/cpf
version: '3.7'
volumes:
  grafdata: ~
  irisdata: ~
